server:
  port: 8800
  tomcat:
    max-http-form-post-size: 1024MB
spring:
  application:
    name: "wps-file-storage"
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  cloud:
    consul:
      host: "202.114.148.161"
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
        prefer-ip-address: true
        heartbeat:
          enabled: true

io:
  github:
    swsk33:
      file-lift:
        core:
          storage-method: "minio"
        minio:
          endpoint: "http://202.114.148.161:9000"
          access-key: "m1TzA2Myp6cIH8spG2o9"
          secret-key: "5iDrm6iM8WahKYyk2hYsAaYjDsOl68tPk68VvyOb"
          bucket-name: "demo"