server:
  port: 8800
  tomcat:
    max-http-form-post-size: 10240MB
spring:
  application:
    name: "wps-file-storage"
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  cloud:
    consul:
      host: "${CONSUL_HOST:127.0.0.1}"
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
        prefer-ip-address: true
        heartbeat:
          enabled: true

io:
  github:
    swsk33:
      file-lift:
        core:
          storage-method: "minio"
        minio:
          endpoint: "http://${MINIO_HOST:127.0.0.1}:${MINIO_PORT:9000}"
          access-key: "${MINIO_ACCESS_KEY:admin}"
          secret-key: "${MINIO_SECRET_KEY:12345678}"
          bucket-name: "${MINIO_BUCKET:wps-file}"