server:
  port: 8000

spring:
  application:
    name: "wps-gateway"
  codec:
    max-in-memory-size: 10240MB
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  cloud:
    consul:
      host: "${CONSUL_HOST:127.0.0.1}"
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
        prefer-ip-address: true
        heartbeat:
          enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # PyWPS服务
        - id: "py-wps"
          uri: "lb://py-wps"
          predicates:
            - "Path=/api/wps/**"
          filters:
            - RewritePath=/api/wps/(?<remaining>.*), /${remaining}
        # 分布式文件服务
        - id: "file-upload"
          uri: "lb://wps-file-storage"
          predicates:
            - "Path=/api/file/**"