server:
  port: 9000

spring:
  application:
    name: "gateway"
  cloud:
    consul:
      host: "202.114.148.161"
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
        prefer-ip-address: true
        heartbeat:
          enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: "path"
          uri: "lb://executor"
          predicates:
            - "Path=/api/executor/**"