server {
    listen 80;
    server_name cloud-geo;
    client_max_body_size 10G;

    # 静态页面
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # 兼容Vue Router
        try_files $uri $uri/ /index.html;
    }

    # 转发请求
    location /api {
        proxy_pass http://cloud-geo-gateway:8000;
    }
}