spring:
  application:
    name: "wps-executor"
  cloud:
    consul:
      host: "202.114.148.161"
      port: 8500
      discovery:
        service-name: "executor"
        instance-id: "${spring.application.name}-${spring.cloud.client.hostname}-${server.port}"
        prefer-ip-address: true
        # ip-address: "139.223.23.56"
        heartbeat:
          enabled: true
com:
  gitee:
    swsk33:
      executor:
        host: "127.0.0.1"
        port: 5000
        base-path: "/api"