apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-geo.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  LANG: "C.UTF-8"
  DEPLOY_MODE: {{ .Values.pyService.deployMode | quote }}