apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-geo.fullname" . }}-mongodb-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-geo.fullname" . }}-redis-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-geo.fullname" . }}-minio-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-geo.fullname" . }}-consul-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.consul.storage }}
{{- range $i := until (int .Values.pyService.replicas) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-geo.fullname" $ }}-py-{{ add $i 1 }}-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.pyService.storage }}
{{- end }}