apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-geo.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mongo-root-password: {{ .Values.mongodb.rootPassword | b64enc }}
  redis-password: {{ .Values.redis.password | b64enc }}
  minio-root-password: {{ .Values.minio.rootPassword | b64enc }}